### ISSUE TITLE
`/*` breaks indenting

### ISSUE THREAD

**Issue by ben-turner** [chr4/nginx.vim#3] opened 2017-08-31 18:36 UTC
First off, thank you for publishing this plugin—syntax highlighting is super nice to have.

However, I've had to turn off indenting because of how the plugin deals with `/*`. I often use patterns like `include /etc/nginx/conf.d/*.nginx` but it seems that cindent treats this as the start of a multi-line comment and ruins the formatting for the entire file.

Not being much of a vim wizard, I can't find a solution to fix it myself and create a PR so I'm hoping someone else can fix it.

![image](https://user-images.githubusercontent.com/7623873/29939368-76c7f258-8e40-11e7-9e44-f9f11b506d36.png)

**Comment by chr4** [comment] 2017-09-01 12:15
Thanks for your report!

I've tried reproducing your issue by inserting `include /etc/nginx/conf.d/*.nginx;` into one of my nginx config files, but it worked as expected. Also trying `/*` at random places hat no effect on the syntax.

Can you double-check whether there are other plugins active, or a special vim configuration on your end? `/* comment */` is used in C-style languages, so maybe that's a hint where to look for?

**Comment by ben-turner** [comment] 2017-09-01 18:19
I don't immediately see any other plugins that could be causing that but I'll look some more.

I probably should have included this in the initial issue, but I can reproduce the issue like this:
- `:new`
- `:set ft=nginx`
- `i` (insert mode in new file)
- Type `include /etc/nginx/conf.d/*.nginx`
- Press Enter > cursor goes down one line and right to the same column as the period after the asterisk.
- Any subsequent new lines will start in the same column.

I can confirm that it's cindent treating the `/*` as a comment because if I add `# */` to the end of the "include" line, it seems to fix the problem.

**Comment by chr4** [comment] 2017-09-01 22:37
Thank you for the clarification and the instructions! I could reproduce the problem. 
This looks indeed like a bug.

I'm currently not aware of fiddeling with `/* */` somewhere, but I'll dig into it.

**Comment by chr4** [comment] 2017-09-01 22:47
This is due to the `setlocal cindent` statement in `ftplugin/nginx.vim`.

**Comment by chr4** [comment] 2017-09-01 22:56
A fast solution would be to drop `cindent` in favor of [smartindent](http://vimdoc.sourceforge.net/htmldoc/options.html#%27smartindent%27). This solves your problem, but I'd apprechiate feedback whether this actually messes other indention up:

indent/nginx.vim
```vim
setlocal smartindent " instead of setlocal cindent
```

**Comment by ben-turner** [comment] 2017-09-01 23:16
cindent definitely messes with comments. It might be possible to use [cinoptions](http://vimdoc.sourceforge.net/htmldoc/indent.html#cinoptions-values) `c` or `C` setting to fix this.

> 	cN    Indent comment lines after the comment opener, when there is no other text with which to align, N characters from the comment opener.  (default 3).  See also |format-comments|.

    cino=                    cino=c5
      /*                       /*
         text.                      text.
      */                       */
 
> CN    When N is non-zero, indent comment lines by the amount specified with the c flag above even if there is other text behind the comment opener.  (default 0).

    cino=c0                    cino=c0,C1
      /********                  /********
        text.                    text.
      ********/                  ********/

**Comment by ben-turner** [comment] 2017-09-01 23:17
Digging in further, it looks like the [comments setting](http://vimdoc.sourceforge.net/htmldoc/change.html#format-comments) might help. Just trying to find the correct setting now.

**Comment by chr4** [comment] 2017-09-01 23:19
I've actually tried this, but as far as I understood/ tested `cino=cN` is a relative setting. This results in the following:

```
#c3 (standart)
test /*
        test

# c0
test /*
     test
```

**Comment by ben-turner** [comment] 2017-09-01 23:24
That's also how I understood it. I'm thinking if we can `:set comments` to the right value we should be able to disable that type of comment.

**Comment by chr4** [comment] 2017-09-01 23:34
`set comments=b:#` and `set comments=` don't make a difference here. I assume that `cindent` overrides a lot of formatting-options (I think I saw something like that when skipping through the documentation).

My current guess is to try `smartindent`, and if that turns out to be not enough, write a custom `indentexpr`. 

Curious whether you have more luck though.

**Comment by HLFH** [comment] 2022-12-01 10:41
Fixed by https://github.com/chr4/nginx.vim/pull/20.
Can this issue be closed and the PR merged?

Thanks!

**Closed** 2022-12-01 12:54 UTC

**Comment by chr4** [comment] 2022-12-01 13:06
PR merged. Thanks for contributing!
